### ISSUE TITLE
Создание tour detail

### ISSUE THREAD

**Issue by OVERDOZZZE** [OVERDOZZZE/Snail-trip-backend#9]
### Подробная информация:
- Название тура
- Описание тура
- Фотографии тура
- Рейтинг тура (пока что заглушка)
- Гид тура
- Область проведения

**Comment by Alim00701** [comment]
Added automatic entry of slugs in the admin panel, corrected slugs in models and added the get_absolute_url function, created a serializer and made views according to CBV rules
